version: '3.8'
services:
  web:
    build: backend/
    container_name: bryn_mawr_eats_web
    # env_file:
    #   - ./.env
    command: python manage.py runserver 0.0.0.0:8000
    # command: tail -f /dev/null
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - '8000:8000'
  nuxt:
    build:
      context: frontend/
    container_name: bryn_mawr_eats_nuxt
    environment:
      - API_BASE=http://localhost:8000/api/v1
    ports:
      - '3000:3000'
      - '24678:24678'
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules/
