# Generated by Django 4.1.5 on 2023-11-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipeingredient_quantity_recipeingredient_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='unit',
        ),
    ]
