# Generated by Django 4.1.5 on 2023-11-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_groceryitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryaisle',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
