# Generated by Django 4.1.5 on 2024-01-14 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_groceryitem_options_recipe_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipe_ingredients', to='recipes.recipe'),
        ),
    ]
