# Generated by Django 4.1.5 on 2024-01-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_unit_name_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
