# Generated by Django 4.1.5 on 2024-03-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_protect_recipe_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groceryaisle',
            options={'ordering': ['name']},
        ),
    ]
